version: "3.9"  # optional since v1.27.0
services:
  db:
    container_name: "foodPicker_db"
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foodDB
    ports:
      - '5431:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: